### ISSUE TITLE
Small square

### ISSUE THREAD

**Issue by kikachangames** [MishaIac/iwaihime-tool#1]
First of all, congratulations on the tool. I'm using it to translate Iwaihime into Portuguese. It worked perfectly, but at the end of each line of text and next to the character's name, a small square appears. Do you know how I can fix it?
![Captura de tela de 2024-09-30 20-08-14](https://github.com/user-attachments/assets/7f8b8659-dcd9-4b7a-8c0d-b4e48264a0b7)

**Comment by MishaIac** [comment]
send please txt file, that you translated

**Comment by MishaIac** [comment]
convert all newlines in txts from Unix (LF) to Windows (CR LF), or update main.py

**Comment by kikachangames** [comment]
![Captura de tela de 2024-10-03 18-33-18](https://github.com/user-attachments/assets/db93d470-b4a7-4aa8-8d0b-017f96d909a0)
I used the updated main.py and now it works perfectly. Thank you!
